import 'package:flutter/material.dart';
import 'package:study_quest/models/event.dart';

class EventProvider extends ChangeNotifier {
  final List<Event> _events = [];

  List<Event> get events => _events;

  DateTime _selectedDate = DateTime.now();

  DateTime get selectedDate => _selectedDate;

  void setDate(DateTime date) => _selectedDate = date;

  List<Event> get eventsOfSelectedDate => _events;

  void addEvent(Event event) {
    _events.add(event);
    notifyListeners();
  }

  void deleteEvent(Event event) {
    _events.remove(event);
    notifyListeners();
  }

  void updateEvent(Event newEvent, Event oldEvent) {
    final index = _events.indexOf(oldEvent);
    _events[index] = newEvent;
    notifyListeners();
  }

  // Limpar todos os eventos
  void clearEvents() {
    _events.clear();
    notifyListeners();
  }

  // Verifica se um intervalo de tempo está disponível
  bool isTimeSlotAvailable(DateTime from, DateTime to) {
    for (var event in _events) {
      if (from.isBefore(event.to) && to.isAfter(event.from)) {
        return false; // Conflito de horário
      }
    }
    return true; // Horário disponível
  }

  // Remover apenas eventos gerados automaticamente
  void removeAutoGeneratedEvents() {
    _events.removeWhere((event) => event.isAutoGenerated);
    notifyListeners();
  }
}